### PR TITLE
Docs/change events

### PR DESCRIPTION
**Pull request by james2doyle**
I was browsing the source code and noticed that there is a change event that is fired on the nodes when attributes are updated. I couldn’t find this documented anywhere so I added it in the Docs section.

You can see a demo of what I wrote here: https://codesandbox.io/s/konva-attribute-change-event-nglfx

### CODE REVIEW

**Comment by lavrton** [comment]
Thanks a lot for your contribution, but I am going to reject it.

`attributeChange` event is here and fully works. But probably that feature will be removed at some point. Even if it is not removed, I think using it is an antipattern and should be avoided. It should only be used in Konva internals (not in public API).

**Comment by james2doyle** [comment]
Ah ok. Thanks for the update. Personally, I would love to have a `change` event that just fires on anything changing. The reason being that I have a store/state management system that I want to keep in sync with the canvas. So I want to call `.toJSON` on debounced changes.

A question actually. I also noticed there is a `add` event that is fired on Container. Can I document that? I am using it in my app to delay adding event handlers to certain nodes

**Comment by lavrton** [comment]
> So I want to call .toJSON on debounced changes.

I don't understand what is the use case here. There are three ways to change a property of a node.

1. Manually `node.fill('red')`
2. Dragging
3. Transforming.

For 2 and 3 there are `dragmove` and `transform` events. For the first one, if you changed a property, you know that the is a change, so you can schedule `toJSON()` call.

For tweens there is `onFinish` callback.

Same with `add` event. Only you (from the code) can add an element. So you schedule a work here from the same place.

**Comment by james2doyle** [comment]
I don’t want to have a `node.toJSON` at the end of all my events though. 

```
node.on('dragend', () => {
  // ...normal stuff
  saveState(node.toJSON());
});
node.on('click', () => {
  // ...normal stuff
  node.to({
    stroke: 'black',
    strokeWidth: 3,
    onFinish: () => saveState(node.toJSON())
  });
});
node.on('drop-arrow', () => { // custom event for when I draw arrows between nodes
  // ...drawing stuff, adding children, etc
  saveState(node.toJSON());
});
```

I would rather do this:

```
node.on('dragend', () => {
  // ...normal stuff
});
node.on('click', () => {
  // ...normal stuff
  node.to({
    stroke: 'black',
    strokeWidth: 3,
  });
});
node.on('drop-arrow', () => { // custom event for when I draw arrows between nodes
  // ...drawing stuff, adding children, etc
});
// one event with my "save" code
node.on('change', () => {
  saveState(node.toJSON())
});
```

For the Container `add` event issue, I'm using `Node.Create` so I'm not calling `layer.add` for each item. Does that matter?

**Pull request closed without merging**
