### PR TITLE
Fix events

### PR DESCRIPTION
**Pull request by jovination**
Stupid mistake on doing the events, this should fix them.

Any chance of fixing generation so that it does not cause errors? I cannot seem to get around them and given this is the second pr that had some issues I feel being able to test it would be extremely beneficial.

### CODE REVIEW

**Comment by lavrton** [comment]
What error do you have? I think everything should be fine. Try to remove `node_modules` and reinstall. Try to clear npm cache.

**Comment by jovination** [comment]
I tried on 2 different platforms, both have issues with jsdoc, but I will keep trying, its both ubuntu and windows that I have tried anyway.

**Comment by lavrton** [comment]
install and build works for me at windows and linux.

**Comment by jovination** [comment]
Wierd. Must be something with my setup, though unsure what it is. If i figure it out and its something fixable by the repo then ill do a pull request or open an issue, might be something stupid like umasks though or node version (ubuntu has a messed up way to use node, and windows damn filepaths/permissions).

**Comment by lavrton** [comment]
You can manually delete `gulp-jsdoc` from deps and remove `docs` task from `gulpfile.js`.

**Pull request merged**
