### PR TITLE
Additional svelte-konva docs

### PR DESCRIPTION
**Pull request by TeyKey1**
Adds additional Svelte doc pages.

### CODE REVIEW

**Comment by lavrton** [comment]
Wow, that is nice.

BTW, I suggest making sure that all essential docs are still placed in README of svelte-konva. Docs on the website are more like tutorials, demos.

**Comment by TeyKey1** [comment]
Yeah that's my intention as well. Currently keeping it as close as possible to the vue docs in terms of content. Gonna add some svelte-specifics additionally where it makes sense.

**Comment by TeyKey1** [comment]
@lavrton can you also please update the webpage link of the svelte-konva repo to the Konva webpage instead of my github.io page? Don't have permission to do that

**Comment by lavrton** [comment]
@TeyKey1 I upgraded your access. You should be able to do it by yourself. Please confirm.

**Comment by TeyKey1** [comment]
Great, works now. Thanks

**Pull request merged**
